# Generated by Django 4.2.6 on 2023-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_remove_message_chat_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
