# Generated by Django 4.2.6 on 2023-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_report_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
