# Generated by Django 4.2.6 on 2023-12-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
